backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

site_url: https://gatsby-online-cv.netlify.app/

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "experience"
    label: "Experience"
    folder: "content/experience"
    create: true
    title: "{{position}}-{{company}}"
    slug: "index"
    media_folder: ""
    public_folder: ""
    editor:
      preview: false
    fields:
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
